update piple

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -282,21 +282,33 @@ jobs:
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
-      - image: cimg/python:3.7-node
+      - image: ansible/centos7-ansible
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints: ["b2:9f:fe:f4:2a:f1:6b:8f:45:ca:78:ea:de:cb:da:c1"]
-      - python/install-packages:
-          args: ansible
       - attach_workspace:
           at: ~/
       - run:
-          name: Install aws dependencies
+          name: Install dependencies
           command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
+            yum install -y tar gzip npm nodejs ansible
+      - run:
+          name: "Set environment"
+          command: |
+            cd backend
+            touch .env
+            echo ENVIRONMENT=production >> .env
+            echo NODE_ENV=production >> .env
+            echo TYPEORM_CONNECTION=postgres >> .env
+            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
+            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
+            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
+            echo TYPEORM_HOST=$TYPEORM_HOST >> .env
+            echo TYPEORM_PORT=$TYPEORM_PORT >> .env
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
       - run:
           name: Deploy backend
           command: |
@@ -318,46 +330,51 @@ jobs:
 
   smoke-test:
     docker:
-      - image: amazon/aws-cli
+      - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
       - checkout
-      - aws-cli/setup
+      - run:
+          name: Install dependency
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscli.zip"
+            unzip awscli.zip
+            sudo ./aws/install
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws --region us-east-1 \
+              ec2 describe-instances \
+              --filters \
+              "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
+              --output text 2>&1)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL=${API_URL}"
+            echo "${API_URL}" > backend/api_url
+            cat backend/api_url
+      - run:
+          name: Backend smoke test.
+          command: |
+            sleep 10
+            export API_URL=$(cat backend/api_url)
+            echo "API_URL=${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
             echo ${URL} 
-            test_result=$(curl -s "$URL")
-            if echo $test_result | grep "Welcome" > /dev/null
+            if curl -s ${URL} | grep "Welcome"
             then
-              echo "Frontend test passed"
-              echo $test_result
+              # Change this to 0 after the job fails
               exit 0
             else
-              echo $test_result
-              exit 1
-            fi
-      - run:
-          name: Backend smoke test.
-          command: |
-            export BACKEND_PUBLIC_IP=$(aws --region us-east-1 ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicDnsName' --output text)
-            echo "${BACKEND_PUBLIC_IP}"
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            echo "${API_URL}"
-            curl --version
-            # When the backend server is not ready, let retry upto 6mins
-            test_result=$(eval curl \
-              --verbose --fail \
-              --retry 50 --retry-max-time 360 --retry-all-errors \
-              --url "$API_URL/api/status")
-            if echo $test_result | grep "ok" > /dev/null
-            then
-              echo "Backend test passed"
-              echo $test_result
-              exit 0
-            else
-              echo $test_result
               exit 1
             fi
       # Here's where you will add some code to rollback on failure 
